### ISSUE TITLE
ユーザー名を入力したら進捗を表示できるようにしてほしい

### ISSUE THREAD

**Issue by stone725** [zakuro9715/aojoi#1]
はわわ～っ！(実装できるのならお願いします)

**Comment by zakuro9715** [comment]
https://twitter.com/zakuro9715/status/653209345849626626

https://twitter.com/zakuro9715/status/653209633041940485

**Comment by zakuro9715** [comment]
やろうとは思っているので、そのうち実装します

**Comment by zakuro9715** [comment]
実装しました
